### ISSUE TITLE
SOME STATION RESTRICTED 

### ISSUE THREAD

**Issue by ahmadnbl20** [xspanger3770/GlobalQuake#289]
Station provided by BMG-Net FDSN code : IA (Indonesia) . channels and network are unavailable or restricted. 

how can i solve this problem or get access to station network?. since station worked in indoneisa in this app available only limited to station provided by GFZ. 

For Example for java island itself only 4 station (in 1000km x 300 km area) available to launch in this app..... slows down data transmission during earthquake event.

Thank you

<img width="959" alt="unavailable station" src="https://github.com/xspanger3770/GlobalQuake/assets/126788798/409328ff-57ad-4bbf-8d9d-e66c37692e52">

**Comment by AyanamiJoss** [comment]
Hello!, the Indonesian Seismic Network with IA network code is _**restricted and it is not possible to access it publicly**_, which is why it appears that it is not available, for this **you need the Data Server (Seedlink)** of the network you want to add to GlobalQuake, in this case Indonesia, I don't know if you can request it from the BMKG, although they will most likely **reject your request**
