### ISSUE TITLE
Globalquake does not support Quakelink FDSNWS

### ISSUE THREAD

**Issue by Will-Stewart** [xspanger3770/GlobalQuake#310]
Trying to use a quakelink FNSNWS server results in errors due to the different paths on the URL. A demo of this type of FDSNWS server can be found at https://demo.gempa.de/quakelink/stations/ . They are compatible with IRIS syntax (https://service.iris.edu/fdsnws/station/1/) they just use a different url structure.

**Comment by AyanamiJoss** [comment]
For many reasons (either because it is **simpler to obtain** and has a **less complex structure** than QuakeLink stations) the **FDSNWS Station** XML is used, I recommend in these cases that you want to use QuakeLink stations is to **extract** the stations in **XML format** and import those stations to **SeisComP** (**_QuakeLink stations are in scml format_**) and **turn on** the _FDSNWS module_ in SeisComP and use the IP "**http://localhost:8080/fdsnws/station/1/**".

**Comment by Will-Stewart** [comment]
Made my own Seiscomp server to do this and works perfectly. Thank you ! :+1:
