### ISSUE TITLE
Clarify additional licenses

### ISSUE THREAD

**Issue by danieldegroot2** [xspanger3770/GlobalQuake#74]
There are currently two additional licenses which seem to be unused. I would suggest removing these or claryifing their purpose in the readme.

**Comment by xspanger3770** [comment]
The two licenses you are talking about (`LICENCE_J` and `LICENCE_K`) are there because I use sound effects from 2 different programs - namely [JQuake](https://jquake.net/) and [KiwiMonitor](https://kiwimonitor.amebaownd.com/) as they are under the developer's copyright and I believe they should be included.
Will add note to readme
