### ISSUE TITLE
Select Stations Save Upon ReLaunch

### ISSUE THREAD

**Issue by lab596** [xspanger3770/GlobalQuake#81]
I'm not sure if this is an intended feature but the stations that are selected in the `Select Stations` UI are saved and displayed as "selected" upon relaunching not just the `Select Station` UI but also the entire application

**Comment by xspanger3770** [comment]
If I understand the question correctly then yes I intended the app to work like this - the `Select Stations` UI and the initial UI (I call it `Database Manager` UI) are all connected and currently the database state is saved in these two cases:
- Initial loading phase finishes
- the `Database Manager` UI is closed (either directly or by pressing `Launch GlobalQuake`

This should be good compromise because the saving takes quite a long time and would cause lags if done frequently
